// react-compare/src/components/WeatherCard.tsx
import type { WeatherForecast } from '../types/weather';

interface WeatherCardProps {
  forecast: WeatherForecast;
}

export const WeatherCard = ({ forecast }: WeatherCardProps) => {
  return (
    <div className="weather-card">
      <div className="card-day">{forecast.name}</div>
      <img
        className="card-icon"
        src={forecast.icon}
        alt={forecast.shortForecast}
      />
      <div className="card-temps">
        <span className="card-high">{forecast.temperature}°</span>
        <span className="card-low">{forecast.temperatureUnit}</span>
      </div>
      <div className="card-description">{forecast.shortForecast}</div>
    </div>
  );
};

// angular-compare/src/app/components/weather-card/weather-card.component.ts
import { Component, input } from '@angular/core';
import { WeatherForecast } from '../../types/weather';

@Component({
  selector: 'app-weather-card',
  standalone: true,
  templateUrl: './weather-card.component.html'
})
export class WeatherCardComponent {
  forecast = input.required<WeatherForecast>();
}
<div class="weather-card">
  <div class="card-day">{{ forecast().name }}</div>
  <img class="card-icon" [src]="forecast().icon" [alt]="forecast().shortForecast" />
  <div class="card-temps">
    <span class="card-high">{{ forecast().temperature }}°</span>
    <span class="card-low">{{ forecast().temperatureUnit }}</span>
  </div>
  <div class="card-description">{{ forecast().shortForecast }}</div>
</div>
