// react-compare/src/components/ForecastFilter.tsx
import { useState } from 'react';
import { WeatherCard } from './WeatherCard';
import type { WeatherForecast } from '../types/weather';

interface ForecastFilterProps {
  forecast: WeatherForecast[];
  onFilterChange: (filteredForecast: WeatherForecast[]) => void;
}

export const ForecastFilter = ({ forecast, onFilterChange }: ForecastFilterProps) => {
  const [showOnlyRainy, setShowOnlyRainy] = useState(false);

  const handleToggle = (checked: boolean) => {
    setShowOnlyRainy(checked);

    const filteredForecast = checked
      ? forecast.filter(day =>
          day.probabilityOfPrecipitation?.value &&
          day.probabilityOfPrecipitation.value > 30
        )
      : forecast;

    onFilterChange(filteredForecast);
  };

  const filteredForecast = showOnlyRainy
    ? forecast.filter(day =>
        day.probabilityOfPrecipitation?.value &&
        day.probabilityOfPrecipitation.value > 30
      )
    : forecast;

  return (
    <>
      <label className="filter-toggle">
        <input
          type="checkbox"
          checked={showOnlyRainy}
          onChange={(e) => handleToggle(e.target.checked)}
        />
        Show only rainy days
      </label>
      <div className="forecast-grid">
        {filteredForecast.map((day) => (
          <WeatherCard key={day.number} forecast={day} />
        ))}
        {filteredForecast.length === 0 && showOnlyRainy && (
          <div className="no-results">No rainy days in the forecast! ☀️</div>
        )}
      </div>
    </>
  );
};

// angular-compare/src/app/components/forecast-filter/forecast-filter.component.ts
import { Component, input, output, signal, computed, Output, EventEmitter } from '@angular/core';
import { WeatherCardComponent } from '../weather-card/weather-card.component';
import type { WeatherForecast } from '../../types/weather';

@Component({
  selector: 'app-forecast-filter',
  imports: [WeatherCardComponent],
  templateUrl: './forecast-filter.component.html'
})
export class ForecastFilterComponent {
  public readonly forecast = input.required<WeatherForecast[]>();
  public readonly filterChange = output<WeatherForecast[]>();

  // The old skool way to pass events up to the parent
  @Output() public oldSkoolFilterChange = new EventEmitter<WeatherForecast[]>();

  public readonly showOnlyRainy = signal(false);

  public readonly filteredForecast = computed(() => {
    const forecastData = this.forecast();
    return this.showOnlyRainy()
      ? forecastData.filter(day =>
          day.probabilityOfPrecipitation?.value &&
          day.probabilityOfPrecipitation.value > 30
        )
      : forecastData;
  });

  toggleFilter(event: Event) {
    const checked = (event.target as HTMLInputElement).checked;
    this.showOnlyRainy.set(checked);
    this.filterChange.emit(this.filteredForecast());
  }
}

<label class="filter-toggle">
  <input
    type="checkbox"
    [checked]="showOnlyRainy()"
    (change)="toggleFilter($event)"
  />
  Show only rainy days
</label>
<div class="forecast-grid">
@for (day of filteredForecast(); track day.number) {
  <app-weather-card [forecast]="day" />
}
@if (filteredForecast().length === 0 && showOnlyRainy()) {
  <div class="no-results">No rainy days in the forecast! ☀️</div>
}
