// react-compare/src/components/CurrentWeather.tsx
import { useState } from 'react';
import type { WeatherState } from '../types/weather';

interface CurrentWeatherProps {
  data: WeatherState;
}

export const CurrentWeather = ({ data }: CurrentWeatherProps) => {
  const [showCelsius, setShowCelsius] = useState(false);

  if (!data.currentWeather) return null;

  const displayTemp = showCelsius ?
    Math.round((data.currentWeather.temperature - 32) * 5/9) :
    data.currentWeather.temperature;
  const displayUnit = showCelsius ? 'C' : 'F';

  return (
    <div className="current-weather">
      <h2 className="location-name">{data.location}</h2>
      <div className="current-temp">
        {displayTemp}°{displayUnit}
        <button
          className="temp-toggle"
          onClick={() => setShowCelsius(!showCelsius)}
          title={`Switch to ${showCelsius ? 'Fahrenheit' : 'Celsius'}`}
        >
          °{showCelsius ? 'F' : 'C'}
        </button>
      </div>
      <div className="weather-description">
        {data.currentWeather.shortForecast}
      </div>
      <div className="weather-details">
        <div className="detail-item">
          <div className="detail-label">Wind</div>
          <div className="detail-value">
            {data.currentWeather.windSpeed} {data.currentWeather.windDirection}
          </div>
        </div>
        {data.currentWeather.probabilityOfPrecipitation?.value !== null && (
          <div className="detail-item">
            <div className="detail-label">Rain Chance</div>
            <div className="detail-value">
              {data.currentWeather.probabilityOfPrecipitation!.value}%
            </div>
          </div>
        )}
        <div className="detail-item">
          <div className="detail-label">Period</div>
          <div className="detail-value">{data.currentWeather.name}</div>
        </div>
      </div>
    </div>
  );
};

// angular-compare/src/app/components/current-weather/current-weather.component.ts
import { Component, inject } from '@angular/core';
import { WeatherService } from '../../services/weather.service';

@Component({
  selector: 'app-current-weather',
  standalone: true,
  template: `
    @if (weatherService.currentWeather()) {
      <div class="current-weather">
        <h2 class="location-name">{{ weatherService.location() }}</h2>
        <div class="current-temp">
          {{ weatherService.currentWeather()!.temperature }}°{{
            weatherService.currentWeather()!.temperatureUnit
          }}
        </div>
        <div class="weather-description">
          {{ weatherService.currentWeather()!.shortForecast }}
        </div>
        <div class="weather-details">
          <div class="detail-item">
            <div class="detail-label">Wind</div>
            <div class="detail-value">
              {{ weatherService.currentWeather()!.windSpeed }}
              {{ weatherService.currentWeather()!.windDirection }}
            </div>
          </div>
          @if (
            weatherService.currentWeather()!.probabilityOfPrecipitation
              ?.value !== null
          ) {
            <div class="detail-item">
              <div class="detail-label">Rain Chance</div>
              <div class="detail-value">
                {{
                  weatherService.currentWeather()!.probabilityOfPrecipitation!
                    .value
                }}%
              </div>
            </div>
          }
          <div class="detail-item">
            <div class="detail-label">Period</div>
            <div class="detail-value">
              {{ weatherService.currentWeather()!.name }}
            </div>
          </div>
        </div>
      </div>
    }
  `
})
export class CurrentWeatherComponent {
  weatherService = inject(WeatherService);
}

@if (currentWeather()) {
  <div class="current-weather">
    <h2 class="location-name">{{ location() }}</h2>
    <div class="current-temp">
      {{ displayTemp() }}°{{ displayUnit() }}
      <button
        class="temp-toggle"
        (click)="toggleTempUnit()"
        [title]="'Switch to ' + (showCelsius() ? 'Fahrenheit' : 'Celsius')"
      >
        °{{ showCelsius() ? 'F' : 'C' }}
      </button>
    </div>
    <div class="weather-description">
      {{ currentWeather()!.shortForecast }}
    </div>
    <div class="weather-details">
      <div class="detail-item">
        <div class="detail-label">Wind</div>
        <div class="detail-value">
          {{ currentWeather()!.windSpeed }}
          {{ currentWeather()!.windDirection }}
        </div>
      </div>
      @if (currentWeather()!.probabilityOfPrecipitation?.value !== null) {
        <div class="detail-item">
          <div class="detail-label">Rain Chance</div>
          <div class="detail-value">
            {{ currentWeather()!.probabilityOfPrecipitation!.value }}%
          </div>
        </div>
      }
      <div class="detail-item">
        <div class="detail-label">Period</div>
        <div class="detail-value">{{ currentWeather()!.name }}</div>
      </div>
    </div>
  </div>
}
