// angular-compare/src/app/components/forecast-list/forecast-list.component.ts
import { Component, inject, computed, signal } from '@angular/core';
import { WeatherResourceService } from '../../services/weather-resource.service';
import { ForecastFilterComponent } from '../forecast-filter/forecast-filter.component';
import type { WeatherForecast } from '../../types/weather';

@Component({
  selector: 'app-forecast-list',
  imports: [ForecastFilterComponent],
  templateUrl: './forecast-list.component.html'
})
export class ForecastListComponent {
  private readonly _weatherResourceService = inject(WeatherResourceService);
  public readonly forecast = computed(() => this._weatherResourceService.forecast());
  public readonly displayCount = signal(0);

  onFilterChange(filteredForecast: WeatherForecast[]) {
    this.displayCount.set(filteredForecast.length);
  }
}

@if (forecast().length > 0) {
  <div class="forecast-section">
    <div class="forecast-header">
      <h3 class="forecast-title">7-Day Forecast</h3>
      <div class="forecast-info">Showing {{ displayCount() }} days</div>
    </div>
    <app-forecast-filter
      [forecast]="forecast()"
      (filterChange)="onFilterChange($event)"
    />
  </div>
}

// react-compare/src/components/ForecastList.tsx
import { useState } from 'react';
import { ForecastFilter } from './ForecastFilter';
import type { WeatherState, WeatherForecast } from '../types/weather';

interface ForecastListProps {
  data: WeatherState;
}

export const ForecastList = ({ data }: ForecastListProps) => {
  const [displayCount, setDisplayCount] = useState(0);

  if (data.forecast.length === 0) return null;

  const handleFilterChange = (filteredForecast: WeatherForecast[]) => {
    setDisplayCount(filteredForecast.length);
  };

  return (
    <div className="forecast-section">
      <div className="forecast-header">
        <h3 className="forecast-title">7-Day Forecast</h3>
        <div className="forecast-info">Showing {displayCount} days</div>
      </div>
      <ForecastFilter
        forecast={data.forecast}
        onFilterChange={handleFilterChange}
      />
    </div>
  );
};
